trigger:
- master

pr:
- '*'

pool:
  vmImage: 'windows-latest'

jobs:
- job: Build
  displayName: 'Build job'
  steps:
  - script: echo 'Hello, Azure DevOps!'
    displayName: 'Run a build step'

- job: Test
  displayName: 'Test job'
  dependsOn: Build
  steps:
  - script: echo 'Running tests...'
    displayName: 'Run tests'

- job: Deploy
  displayName: 'Deploy job'
  dependsOn: Test
  steps:
  - script: echo 'Deploying...'
    displayName: 'Run deployment'

# Add more jobs or adjust as needed
